#!/bin/bash                                                                                                                                                                    #SBATCH -N 1                
#SBATCH -t 59:00         
#SBATCH -p short              
                             
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__45 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__46 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__47 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__48 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__49 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__50 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__51 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__52 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__53 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__54 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__55 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__56 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__57 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__58 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__59 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__60 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__61 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__62 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__63 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__64 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__65 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__66 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__67 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__68 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__69 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__70 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__71 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__72 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__73 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__74 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__75 &
wait
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__76 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__77 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__78 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__79 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__80 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__81 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__82 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__83 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__84 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__85 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__86 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__87 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__88 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__89 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__90 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__91 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__92 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__93 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__94 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__95 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__96 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__97 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__98 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__99 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__100 &
wait
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__101 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__102 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__103 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__104 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__105 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__106 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__107 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__108 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__109 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__110 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__111 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__112 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__113 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__114 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__115 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__116 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__117 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__118 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__119 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__120 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__121 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__122 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__123 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__124 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__125 &
wait
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__126 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__127 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__128 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__129 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__130 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__131 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__132 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__133 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__134 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__135 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__136 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__137 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__138 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__139 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__140 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__141 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__142 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__143 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__144 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__145 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__146 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__147 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__148 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__149 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__150 &
wait
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__151 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__152 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__153 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__154 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__155 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__156 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__157 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__158 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__159 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__160 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__161 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__162 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__163 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__164 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__165 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__166 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__167 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__168 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__169 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__170 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__171 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__172 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__173 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__174 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__175 &
wait
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__176 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__177 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__178 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__179 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__180 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__181 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__182 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__183 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__184 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__185 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__186 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__187 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__188 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__189 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__190 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__191 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__192 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__193 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__194 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__195 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__196 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__197 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__198 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__199 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__200 &
wait
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__201 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__202 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__203 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__204 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__205 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__206 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__207 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__208 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__209 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__210 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__211 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__212 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__213 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__214 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__215 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__216 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__217 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__218 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__219 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__220 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__221 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__222 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__223 &
python 0_main_analyze_discharge.py /projects/wtrcycle/users/edwinhs/IWMI_calibration/code__a__224 &
wait
