#!/bin/bash
#SBATCH -N 1
#SBATCH -t 48:00:00
#SBATCH -p normal

python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__2 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__3 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__4 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__5 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__6 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__7 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__8 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__9 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__10 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__11 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__12 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__13 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__14 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__15 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__16 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__17 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__18 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__19 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__20 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__21 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__22 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__23 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__24 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__25 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__26 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__27 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__28 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__29 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__30 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__31 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__32 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__33 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__34 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__35 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__36 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__37 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__38 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__39 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__40 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__41 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__42 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__43 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__44 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__45 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__46 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__47 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__48 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__49 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__50 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__51 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__52 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__53 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__54 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__55 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__56 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__57 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__58 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__59 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__60 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__61 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__62 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__63 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__64 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__65 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__66 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__67 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__68 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__69 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__70 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__71 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__72 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__73 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__74 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__75 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__76 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__77 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__78 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__79 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__80 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__81 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__82 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__83 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__84 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__85 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__86 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__87 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__88 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__89 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__90 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__91 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__92 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__93 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__94 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__95 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__96 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__97 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__98 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__99 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__100 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__101 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__102 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__103 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__104 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__105 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__106 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__107 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__108 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__109 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__110 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__111 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__112 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__113 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__114 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__115 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__116 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__117 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__118 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__119 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__120 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__121 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__122 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__123 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__124 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__125 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__126 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__127 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__128 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__129 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__130 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__131 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__132 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__133 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__134 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__135 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__136 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__137 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__138 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__139 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__140 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__141 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__142 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__143 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__144 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__145 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__146 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__147 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__148 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__149 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__150 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__151 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__152 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__153 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__154 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__155 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__156 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__157 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__158 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__159 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__160 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__161 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__162 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__163 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__164 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__165 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__166 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__167 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__168 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__169 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__170 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__171 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__172 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__173 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__174 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__175 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__176 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__177 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__178 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__179 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__180 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__181 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__182 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__183 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__184 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__185 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__186 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__187 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__188 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__189 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__190 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__191 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__192 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__193 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__194 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__195 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__196 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__197 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__198 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__199 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__200 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__201 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__202 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__203 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__204 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__205 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__206 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__207 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__208 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__209 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__210 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__211 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__212 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__213 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__214 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__215 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__216 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__217 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__218 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__219 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__220 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__221 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__222 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__223 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__224 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__225 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__226 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__227 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__228 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__229 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__230 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__231 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__232 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__233 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__234 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__235 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__236 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__237 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__238 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__239 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__240 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__241 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__242 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__243 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__244 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__245 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__246 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__247 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__248 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__249 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__250 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__251 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__252 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__253 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__254 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__255 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__256 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__257 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__258 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__259 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__260 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__261 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__262 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__263 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__264 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__265 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__266 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__267 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__268 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__269 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__270 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__271 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__272 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__273 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__274 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__275 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__276 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__277 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__278 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__279 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__280 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__281 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__282 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__283 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__284 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__285 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__286 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__287 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__288 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__289 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__290 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__291 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__292 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__293 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__294 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__295 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__296 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__297 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__298 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__299 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__300 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__301 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__302 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__303 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__304 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__305 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__306 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__307 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__308 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__309 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__310 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__311 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__312 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__313 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__314 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__315 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__316 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__317 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__318 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__319 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__320 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__321 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__322 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__323 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__324 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__325 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__326 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__327 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__328 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__329 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__330 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__331 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__332 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__333 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__334 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__335 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__336 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__337 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__338 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__339 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__340 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__341 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__342 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__343 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__344 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__345 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__346 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__347 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__348 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__349 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__350 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__351 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__352 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__353 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__354 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__355 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__356 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__357 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__358 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__359 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__360 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__361 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__362 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__363 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__364 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__365 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__366 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__367 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__368 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__369 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__370 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__371 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__372 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__373 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__374 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__375 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__376 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__377 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__378 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__379 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__380 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__381 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__382 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__383 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__384 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__385 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__386 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__387 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__388 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__389 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__390 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__391 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__392 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__393 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__394 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__395 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__396 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__397 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__398 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__399 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__400 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__401 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__402 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__403 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__404 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__405 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__406 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__407 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__408 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__409 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__410 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__411 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__412 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__413 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__414 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__415 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__416 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__417 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__418 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__419 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__420 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__421 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__422 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__423 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__424 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__425 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__426 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__427 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__428 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__429 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__430 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__431 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__432 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__433 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__434 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__435 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__436 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__437 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__438 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__439 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__440 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__441 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__442 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__443 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__444 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__445 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__446 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__447 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__448 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__449 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__450 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__451 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__452 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__453 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__454 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__455 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__456 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__457 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__458 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__459 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__460 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__461 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__462 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__463 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__464 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__465 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__466 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__467 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__468 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__469 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__470 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__471 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__472 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__473 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__474 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__475 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__476 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__477 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__478 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__479 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__480 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__481 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__482 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__483 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__484 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__485 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__486 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__487 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__488 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__489 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__490 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__491 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__492 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__493 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__494 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__495 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__496 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__497 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__498 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__499 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__500 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__501 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__502 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__503 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__504 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__505 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__506 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__507 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__508 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__509 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__510 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__511 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__512 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__513 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__514 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__515 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__516 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__517 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__518 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__519 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__520 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__521 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__522 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__523 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__524 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__525 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__526 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__527 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__528 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__529 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__530 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__531 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__532 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__533 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__534 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__535 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__536 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__537 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__538 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__539 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__540 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__541 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__542 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__543 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__544 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__545 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__546 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__547 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__548 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__549 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__550 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__551 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__552 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__553 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__554 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__555 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__556 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__557 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__558 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__559 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__560 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__561 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__562 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__563 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__564 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__565 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__566 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__567 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__568 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__569 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__570 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__571 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__572 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__573 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__574 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__575 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__576 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__577 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__578 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__579 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__580 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__581 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__582 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__583 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__584 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__585 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__586 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__587 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__588 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__589 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__590 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__591 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__592 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__593 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__594 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__595 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__596 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__597 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__598 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__599 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__600 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__601 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__602 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__603 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__604 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__605 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__606 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__607 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__608 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__609 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__610 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__611 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__612 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__613 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__614 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__615 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__616 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__617 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__618 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__619 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__620 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__621 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__622 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__623 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__624 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__625 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__626 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__627 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__628 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__629 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__630 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__631 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__632 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__633 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__634 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__635 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__636 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__637 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__638 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__639 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__640 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__641 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__642 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__643 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__644 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__645 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__646 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__647 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__648 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__649 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__650 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__651 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__652 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__653 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__654 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__655 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__656 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__657 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__658 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__659 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__660 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__661 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__662 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__663 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__664 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__665 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__666 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__667 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__668 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__669 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__670 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__671 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__672 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__673 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__674 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__0 calibration &
wait
