#!/bin/bash
#SBATCH -N 1
#SBATCH -t 48:00:00
#SBATCH -p normal

python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__1 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__2 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__3 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__4 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__5 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__6 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__7 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__8 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__9 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__10 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__11 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__12 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__13 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__14 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__15 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__16 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__17 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__18 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__19 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__20 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__21 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__22 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__23 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__24 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__25 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__26 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__27 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__28 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__29 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__30 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__31 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__32 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__33 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__34 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__35 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__36 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__37 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__38 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__39 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__40 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__41 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__42 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__43 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__44 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__45 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__46 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__47 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__48 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__49 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__50 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__51 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__52 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__53 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__54 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__55 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__56 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__57 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__58 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__59 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__60 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__61 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__62 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__63 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__64 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__65 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__66 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__67 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__68 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__69 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__70 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__71 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__72 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__73 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__74 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__75 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__76 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__77 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__78 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__79 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__80 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__81 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__82 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__83 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__84 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__85 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__86 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__87 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__88 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__89 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__90 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__91 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__92 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__93 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__94 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__95 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__96 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__97 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__98 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__99 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__100 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__101 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__102 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__103 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__104 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__105 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__106 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__107 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__108 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__109 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__110 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__111 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__112 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__113 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__114 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__115 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__116 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__117 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__118 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__119 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__120 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__121 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__122 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__123 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__124 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__125 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__126 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__127 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__128 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__129 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__130 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__131 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__132 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__133 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__134 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__135 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__136 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__137 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__138 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__139 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__140 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__141 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__142 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__143 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__144 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__145 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__146 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__147 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__148 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__149 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__150 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__151 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__152 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__153 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__154 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__155 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__156 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__157 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__158 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__159 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__160 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__161 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__162 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__163 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__164 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__165 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__166 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__167 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__168 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__169 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__170 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__171 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__172 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__173 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__174 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__175 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__176 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__177 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__178 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__179 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__180 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__181 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__182 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__183 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__184 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__185 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__186 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__187 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__188 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__189 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__190 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__191 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__192 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__193 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__194 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__195 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__196 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__197 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__198 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__199 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__200 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__201 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__202 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__203 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__204 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__205 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__206 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__207 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__208 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__209 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__210 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__211 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__212 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__213 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__214 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__215 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__216 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__217 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__218 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__219 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__220 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__221 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__222 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__223 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__224 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__225 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__226 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__227 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__228 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__229 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__230 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__231 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__232 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__233 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__234 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__235 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__236 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__237 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__238 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__239 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__240 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__241 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__242 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__243 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__244 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__245 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__246 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__247 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__248 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__249 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__250 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__251 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__252 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__253 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__254 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__255 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__256 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__257 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__258 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__259 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__260 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__261 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__262 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__263 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__264 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__265 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__266 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__267 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__268 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__269 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__270 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__271 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__272 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__273 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__274 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__275 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__276 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__277 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__278 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__279 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__280 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__281 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__282 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__283 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__284 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__285 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__286 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__287 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__288 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__289 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__290 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__291 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__292 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__293 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__294 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__295 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__296 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__297 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__298 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__299 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__300 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__301 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__302 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__303 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__304 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__305 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__306 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__307 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__308 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__309 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__310 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__311 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__312 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__313 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__314 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__315 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__316 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__317 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__318 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__319 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__320 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__321 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__322 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__323 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__324 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__325 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__326 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__327 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__328 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__329 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__330 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__331 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__332 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__333 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__334 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__335 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__336 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__337 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__338 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__339 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__340 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__341 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__342 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__343 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__344 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__345 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__346 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__347 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__348 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__349 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__350 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__351 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__352 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__353 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__354 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__355 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__356 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__357 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__358 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__359 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__360 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__361 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__362 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__363 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__364 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__365 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__366 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__367 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__368 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__369 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__370 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__371 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__372 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__373 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__374 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__375 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__376 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__377 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__378 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__379 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__380 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__381 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__382 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__383 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__384 calibration &
wait
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__385 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__386 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__387 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__388 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__389 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__390 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__391 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__392 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__393 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__394 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__395 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__396 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__397 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__398 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__399 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__400 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__0 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__401 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__402 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__403 calibration &
python 0_main_analyze_discharge.py /scratch-shared/edwin/sensitivity_analysis/2015_10_XX/code__a__404 calibration &
wait
